// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 2.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'task_management_module';

  static const String assets_animations_loading_find_task_json = 'assets/animations/loading_find_task.json';
  static const String task_management_module$assets_animations_loading_find_task_json = 'packages/task_management_module/assets/animations/loading_find_task.json';

  static const String assets_images_pin_png = 'assets/images/pin.png';
  static const String task_management_module$assets_images_pin_png = 'packages/task_management_module/assets/images/pin.png';
}
